import Head from "next/head";
import { Inter } from "next/font/google";
import Characters from "@src/components/Characters/Characters";
import Loading from "@src/components/Loading/Loading";
import MainCharacter from "@src/components/MainCharacter/MainCharacter";
import Background from "@src/components/Background/Background";
import CharacterAnimationIdle from "@src/components/CharacterAnimationIdle/CharacterAnimationIdle";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Characters></Characters>

        <div className="flex items-center justify-center h-screen w-full fixed">
          <div className="w-[1200px] ">
            <CharacterAnimationIdle>
              <MainCharacter></MainCharacter>
            </CharacterAnimationIdle>
          </div>
        </div>

        <Loading></Loading>
      </main>
    </>
  );
}
